/* ==========================================================================
   LUDO — the money rules of the board game.

   One match costs an entry fee. The winner takes the prize pool; a loss or a quit
   only forfeits that fee (it is never charged twice), so the money a player can
   lose in a match is always exactly one entry fee.

   All three numbers live in CONFIG/LUDO, so the admin can re-price the game
   straight from Firebase without a redeploy — the page and the API both read
   them from here, so the price shown can never disagree with the price charged.
   ========================================================================== */

import { dbGet, dbPut } from './backend'

export type LudoMode = 2 | 4

export type LudoConfig = {
  entryFee: number
  prizes: { 2: number; 4: number }
}

export const DEFAULT_LUDO_CONFIG: LudoConfig = {
  entryFee: 100,
  prizes: { 2: 200, 4: 400 },
}

/** A stored CONFIG/LUDO that was hand-edited to nonsense must not break the
 *  game: every field falls back to the default, never below the entry fee. */
export function normaliseLudoConfig(raw: any): LudoConfig {
  const num = (v: any, fallback: number) => {
    const n = Math.round(Number(v))
    return Number.isFinite(n) && n > 0 ? n : fallback
  }
  const entryFee = num(raw?.entryFee, DEFAULT_LUDO_CONFIG.entryFee)
  return {
    entryFee,
    prizes: {
      2: Math.max(entryFee, num(raw?.prizes?.['2'] ?? raw?.prizes?.[2], DEFAULT_LUDO_CONFIG.prizes[2])),
      4: Math.max(entryFee, num(raw?.prizes?.['4'] ?? raw?.prizes?.[4], DEFAULT_LUDO_CONFIG.prizes[4])),
    },
  }
}

export function isLudoMode(mode: any): mode is LudoMode {
  const n = Number(mode)
  return n === 2 || n === 4
}

/** Prize pool of a mode — the winner takes the whole pool. */
export function ludoPrize(cfg: LudoConfig, mode: LudoMode): number {
  return Number(cfg.prizes[mode]) || DEFAULT_LUDO_CONFIG.prizes[mode]
}

const CACHE_TTL = 60 * 1000
let cached: { at: number; value: LudoConfig } | null = null

/** CONFIG/LUDO, seeded with the defaults on the very first read (same pattern as
 *  the wheel and the daily reward). */
export async function loadLudoConfig(env: any): Promise<LudoConfig> {
  if (cached && Date.now() - cached.at < CACHE_TTL) return cached.value
  let stored: any = null
  try {
    stored = await dbGet(env, 'CONFIG/LUDO')
  } catch {
    stored = null
  }
  if (!stored || typeof stored !== 'object') {
    try {
      await dbPut(env, 'CONFIG/LUDO', DEFAULT_LUDO_CONFIG as any)
    } catch {
      /* best effort — the in-memory default is still correct */
    }
    cached = { at: Date.now(), value: DEFAULT_LUDO_CONFIG }
    return DEFAULT_LUDO_CONFIG
  }
  const value = normaliseLudoConfig(stored)
  cached = { at: Date.now(), value }
  return value
}

/** Match id generated by the browser — the idempotency key of one paid match. */
export function validLudoMatchId(id: any): boolean {
  return /^[A-Za-z0-9_-]{6,48}$/.test(String(id || ''))
}

/** Which bucket a debit comes out of: real money (main) first, then the
 *  bonus/3rd-party money — the same split the wallet page shows. */
export function ludoDebitPlan(balance: { main: number; promo: number }, amount: number) {
  const main = Math.min(Math.max(0, balance.main), amount)
  return { main, promo: Math.max(0, amount - main) }
}
